### ISSUE TITLE
version 2.0.8 throws when requiring in node.

### ISSUE THREAD

**Issue by tikotzky** [KyleAMathews/element-resize-event#17]
version 2.0.7 gracefully handles there not being a `window` when requiring in node.
The latest update throws (see error below).

```bash
$ node -r element-resize-event
/node_modules/element-resize-event/index.js:4
    window.webkitRequestAnimationFrame ||
                                       ^

ReferenceError: window is not defined
    at /node_modules/element-resize-event/index.js:4:40
    at Object.<anonymous> (/node_modules/element-resize-event/index.js:11:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at module.js:660:12
    at Array.forEach (native)

**Comment by KyleAMathews** [comment]
2.0.9 is out with @eligolding's fix
